#ifdef ___LINKER_INFO
; File: "tree.c", produced by Gambit-C v4.2.6
(
402006
" tree"
(" tree")
(
)
(
)
(
" tree"
"get-data"
"get-left"
"get-right"
"in-order"
"insert"
"is-in"
"is-leaf"
"lst->tree"
"make-tree"
"num-leaves"
"tree1"
)
(
)
(
"+"
"<"
"<="
"="
">"
"caddr"
"cadr"
"car"
"cdr"
"display"
"length"
"list"
"newline"
"null?"
"read"
)
 #f
)
#else
#define ___VERSION 402006
#define ___MODULE_NAME " tree"
#define ___LINKER_ID ____20_tree
#define ___MH_PROC ___H__20_tree
#define ___SCRIPT_LINE 0
#define ___GLO_COUNT 27
#define ___SUP_COUNT 12
#define ___LBL_COUNT 123
#include "gambit.h"

___NEED_GLO(___G__20_tree)
___NEED_GLO(___G__2b_)
___NEED_GLO(___G__3c_)
___NEED_GLO(___G__3c__3d_)
___NEED_GLO(___G__3d_)
___NEED_GLO(___G__3e_)
___NEED_GLO(___G_caddr)
___NEED_GLO(___G_cadr)
___NEED_GLO(___G_car)
___NEED_GLO(___G_cdr)
___NEED_GLO(___G_display)
___NEED_GLO(___G_get_2d_data)
___NEED_GLO(___G_get_2d_left)
___NEED_GLO(___G_get_2d_right)
___NEED_GLO(___G_in_2d_order)
___NEED_GLO(___G_insert)
___NEED_GLO(___G_is_2d_in)
___NEED_GLO(___G_is_2d_leaf)
___NEED_GLO(___G_length)
___NEED_GLO(___G_list)
___NEED_GLO(___G_lst_2d__3e_tree)
___NEED_GLO(___G_make_2d_tree)
___NEED_GLO(___G_newline)
___NEED_GLO(___G_null_3f_)
___NEED_GLO(___G_num_2d_leaves)
___NEED_GLO(___G_read)
___NEED_GLO(___G_tree1)

___BEGIN_GLO
___DEF_GLO(0," tree")
___DEF_GLO(1,"get-data")
___DEF_GLO(2,"get-left")
___DEF_GLO(3,"get-right")
___DEF_GLO(4,"in-order")
___DEF_GLO(5,"insert")
___DEF_GLO(6,"is-in")
___DEF_GLO(7,"is-leaf")
___DEF_GLO(8,"lst->tree")
___DEF_GLO(9,"make-tree")
___DEF_GLO(10,"num-leaves")
___DEF_GLO(11,"tree1")
___DEF_GLO(12,"+")
___DEF_GLO(13,"<")
___DEF_GLO(14,"<=")
___DEF_GLO(15,"=")
___DEF_GLO(16,">")
___DEF_GLO(17,"caddr")
___DEF_GLO(18,"cadr")
___DEF_GLO(19,"car")
___DEF_GLO(20,"cdr")
___DEF_GLO(21,"display")
___DEF_GLO(22,"length")
___DEF_GLO(23,"list")
___DEF_GLO(24,"newline")
___DEF_GLO(25,"null?")
___DEF_GLO(26,"read")
___END_GLO


#undef ___MD_ALL
#define ___MD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4 ___D_F64(___F64V1) ___D_F64( \
___F64V2) ___D_F64(___F64V3)
#undef ___MR_ALL
#define ___MR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___MW_ALL
#define ___MW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_M_COD
___BEGIN_M_HLBL
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0__20_tree)
___DEF_M_HLBL(___L1__20_tree)
___DEF_M_HLBL(___L2__20_tree)
___DEF_M_HLBL(___L3__20_tree)
___DEF_M_HLBL(___L4__20_tree)
___DEF_M_HLBL(___L5__20_tree)
___DEF_M_HLBL(___L6__20_tree)
___DEF_M_HLBL(___L7__20_tree)
___DEF_M_HLBL(___L8__20_tree)
___DEF_M_HLBL(___L9__20_tree)
___DEF_M_HLBL(___L10__20_tree)
___DEF_M_HLBL(___L11__20_tree)
___DEF_M_HLBL(___L12__20_tree)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_make_2d_tree)
___DEF_M_HLBL(___L1_make_2d_tree)
___DEF_M_HLBL(___L2_make_2d_tree)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_get_2d_data)
___DEF_M_HLBL(___L1_get_2d_data)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_get_2d_left)
___DEF_M_HLBL(___L1_get_2d_left)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_get_2d_right)
___DEF_M_HLBL(___L1_get_2d_right)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_is_2d_leaf)
___DEF_M_HLBL(___L1_is_2d_leaf)
___DEF_M_HLBL(___L2_is_2d_leaf)
___DEF_M_HLBL(___L3_is_2d_leaf)
___DEF_M_HLBL(___L4_is_2d_leaf)
___DEF_M_HLBL(___L5_is_2d_leaf)
___DEF_M_HLBL(___L6_is_2d_leaf)
___DEF_M_HLBL(___L7_is_2d_leaf)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_insert)
___DEF_M_HLBL(___L1_insert)
___DEF_M_HLBL(___L2_insert)
___DEF_M_HLBL(___L3_insert)
___DEF_M_HLBL(___L4_insert)
___DEF_M_HLBL(___L5_insert)
___DEF_M_HLBL(___L6_insert)
___DEF_M_HLBL(___L7_insert)
___DEF_M_HLBL(___L8_insert)
___DEF_M_HLBL(___L9_insert)
___DEF_M_HLBL(___L10_insert)
___DEF_M_HLBL(___L11_insert)
___DEF_M_HLBL(___L12_insert)
___DEF_M_HLBL(___L13_insert)
___DEF_M_HLBL(___L14_insert)
___DEF_M_HLBL(___L15_insert)
___DEF_M_HLBL(___L16_insert)
___DEF_M_HLBL(___L17_insert)
___DEF_M_HLBL(___L18_insert)
___DEF_M_HLBL(___L19_insert)
___DEF_M_HLBL(___L20_insert)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_lst_2d__3e_tree)
___DEF_M_HLBL(___L1_lst_2d__3e_tree)
___DEF_M_HLBL(___L2_lst_2d__3e_tree)
___DEF_M_HLBL(___L3_lst_2d__3e_tree)
___DEF_M_HLBL(___L4_lst_2d__3e_tree)
___DEF_M_HLBL(___L5_lst_2d__3e_tree)
___DEF_M_HLBL(___L6_lst_2d__3e_tree)
___DEF_M_HLBL(___L7_lst_2d__3e_tree)
___DEF_M_HLBL(___L8_lst_2d__3e_tree)
___DEF_M_HLBL(___L9_lst_2d__3e_tree)
___DEF_M_HLBL(___L10_lst_2d__3e_tree)
___DEF_M_HLBL(___L11_lst_2d__3e_tree)
___DEF_M_HLBL(___L12_lst_2d__3e_tree)
___DEF_M_HLBL(___L13_lst_2d__3e_tree)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_in_2d_order)
___DEF_M_HLBL(___L1_in_2d_order)
___DEF_M_HLBL(___L2_in_2d_order)
___DEF_M_HLBL(___L3_in_2d_order)
___DEF_M_HLBL(___L4_in_2d_order)
___DEF_M_HLBL(___L5_in_2d_order)
___DEF_M_HLBL(___L6_in_2d_order)
___DEF_M_HLBL(___L7_in_2d_order)
___DEF_M_HLBL(___L8_in_2d_order)
___DEF_M_HLBL(___L9_in_2d_order)
___DEF_M_HLBL(___L10_in_2d_order)
___DEF_M_HLBL(___L11_in_2d_order)
___DEF_M_HLBL(___L12_in_2d_order)
___DEF_M_HLBL(___L13_in_2d_order)
___DEF_M_HLBL(___L14_in_2d_order)
___DEF_M_HLBL(___L15_in_2d_order)
___DEF_M_HLBL(___L16_in_2d_order)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_num_2d_leaves)
___DEF_M_HLBL(___L1_num_2d_leaves)
___DEF_M_HLBL(___L2_num_2d_leaves)
___DEF_M_HLBL(___L3_num_2d_leaves)
___DEF_M_HLBL(___L4_num_2d_leaves)
___DEF_M_HLBL(___L5_num_2d_leaves)
___DEF_M_HLBL(___L6_num_2d_leaves)
___DEF_M_HLBL(___L7_num_2d_leaves)
___DEF_M_HLBL(___L8_num_2d_leaves)
___DEF_M_HLBL(___L9_num_2d_leaves)
___DEF_M_HLBL(___L10_num_2d_leaves)
___DEF_M_HLBL(___L11_num_2d_leaves)
___DEF_M_HLBL(___L12_num_2d_leaves)
___DEF_M_HLBL(___L13_num_2d_leaves)
___DEF_M_HLBL(___L14_num_2d_leaves)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_is_2d_in)
___DEF_M_HLBL(___L1_is_2d_in)
___DEF_M_HLBL(___L2_is_2d_in)
___DEF_M_HLBL(___L3_is_2d_in)
___DEF_M_HLBL(___L4_is_2d_in)
___DEF_M_HLBL(___L5_is_2d_in)
___DEF_M_HLBL(___L6_is_2d_in)
___DEF_M_HLBL(___L7_is_2d_in)
___DEF_M_HLBL(___L8_is_2d_in)
___DEF_M_HLBL(___L9_is_2d_in)
___DEF_M_HLBL(___L10_is_2d_in)
___DEF_M_HLBL(___L11_is_2d_in)
___DEF_M_HLBL(___L12_is_2d_in)
___DEF_M_HLBL(___L13_is_2d_in)
___DEF_M_HLBL(___L14_is_2d_in)
___END_M_HLBL

___BEGIN_M_SW

#undef ___PH_PROC
#define ___PH_PROC ___H__20_tree
#undef ___PH_LBL0
#define ___PH_LBL0 1
#undef ___PD_ALL
#define ___PD_ALL ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0__20_tree)
___DEF_P_HLBL(___L1__20_tree)
___DEF_P_HLBL(___L2__20_tree)
___DEF_P_HLBL(___L3__20_tree)
___DEF_P_HLBL(___L4__20_tree)
___DEF_P_HLBL(___L5__20_tree)
___DEF_P_HLBL(___L6__20_tree)
___DEF_P_HLBL(___L7__20_tree)
___DEF_P_HLBL(___L8__20_tree)
___DEF_P_HLBL(___L9__20_tree)
___DEF_P_HLBL(___L10__20_tree)
___DEF_P_HLBL(___L11__20_tree)
___DEF_P_HLBL(___L12__20_tree)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0__20_tree)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(0,0,0,0)
___DEF_GLBL(___L__20_tree)
   ___SET_GLO(9,___G_make_2d_tree,___PRC(15))
   ___SET_GLO(1,___G_get_2d_data,___PRC(19))
   ___SET_GLO(2,___G_get_2d_left,___PRC(22))
   ___SET_GLO(3,___G_get_2d_right,___PRC(25))
   ___SET_GLO(7,___G_is_2d_leaf,___PRC(28))
   ___SET_GLO(5,___G_insert,___PRC(37))
   ___SET_GLO(8,___G_lst_2d__3e_tree,___PRC(59))
   ___SET_GLO(4,___G_in_2d_order,___PRC(74))
   ___SET_GLO(10,___G_num_2d_leaves,___PRC(92))
   ___SET_GLO(6,___G_is_2d_in,___PRC(108))
   ___SET_STK(1,___R0)
   ___SET_R0(___LBL(2))
   ___ADJFP(4)
   ___POLL(1)
___DEF_SLBL(1,___L1__20_tree)
   ___JUMPGLOSAFE(___SET_NARGS(0),26,___G_read)
___DEF_SLBL(2,___L2__20_tree)
   ___SET_STK(-2,___R1)
   ___IF(___NOT(___EQP(___GLO(23,___G_list),___PRM(23,___G_list))))
   ___GOTO(___L14__20_tree)
   ___END_IF
   ___SET_R1(___NUL)
   ___GOTO(___L13__20_tree)
___DEF_SLBL(3,___L3__20_tree)
___DEF_GLBL(___L13__20_tree)
   ___SET_R2(___R1)
   ___SET_R0(___LBL(4))
   ___SET_R1(___STK(-2))
   ___JUMPGLOSAFE(___SET_NARGS(2),8,___G_lst_2d__3e_tree)
___DEF_SLBL(4,___L4__20_tree)
   ___SET_GLO(11,___G_tree1,___R1)
   ___SET_R1(___GLO(11,___G_tree1))
   ___SET_R0(___LBL(5))
   ___JUMPGLOSAFE(___SET_NARGS(1),4,___G_in_2d_order)
___DEF_SLBL(5,___L5__20_tree)
   ___SET_R1(___GLO(11,___G_tree1))
   ___SET_R0(___LBL(6))
   ___JUMPGLOSAFE(___SET_NARGS(1),10,___G_num_2d_leaves)
___DEF_SLBL(6,___L6__20_tree)
   ___SET_R0(___LBL(7))
   ___JUMPGLOSAFE(___SET_NARGS(1),21,___G_display)
___DEF_SLBL(7,___L7__20_tree)
   ___SET_R0(___LBL(8))
   ___JUMPGLOSAFE(___SET_NARGS(0),24,___G_newline)
___DEF_SLBL(8,___L8__20_tree)
   ___SET_R0(___LBL(9))
   ___JUMPGLOSAFE(___SET_NARGS(0),26,___G_read)
___DEF_SLBL(9,___L9__20_tree)
   ___SET_R2(___GLO(11,___G_tree1))
   ___SET_R0(___LBL(10))
   ___JUMPGLOSAFE(___SET_NARGS(2),6,___G_is_2d_in)
___DEF_SLBL(10,___L10__20_tree)
   ___SET_R0(___LBL(11))
   ___JUMPGLOSAFE(___SET_NARGS(1),21,___G_display)
___DEF_SLBL(11,___L11__20_tree)
   ___SET_R0(___STK(-3))
   ___POLL(12)
___DEF_SLBL(12,___L12__20_tree)
   ___ADJFP(-4)
   ___JUMPGLOSAFE(___SET_NARGS(0),24,___G_newline)
___DEF_GLBL(___L14__20_tree)
   ___SET_R0(___LBL(3))
   ___JUMPGLOSAFE(___SET_NARGS(0),23,___G_list)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_make_2d_tree
#undef ___PH_LBL0
#define ___PH_LBL0 15
#undef ___PD_ALL
#define ___PD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_HEAP ___W_R1 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_make_2d_tree)
___DEF_P_HLBL(___L1_make_2d_tree)
___DEF_P_HLBL(___L2_make_2d_tree)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_make_2d_tree)
   ___IF_NARGS_EQ(3,___NOTHING)
   ___WRONG_NARGS(0,3,0,0)
___DEF_GLBL(___L_make_2d_tree)
   ___IF(___EQP(___GLO(23,___G_list),___PRM(23,___G_list)))
   ___GOTO(___L3_make_2d_tree)
   ___END_IF
   ___POLL(1)
___DEF_SLBL(1,___L1_make_2d_tree)
   ___JUMPGLOSAFE(___SET_NARGS(3),23,___G_list)
___DEF_GLBL(___L3_make_2d_tree)
   ___BEGIN_ALLOC_LIST(3,___R3)
   ___ADD_LIST_ELEM(1,___R2)
   ___ADD_LIST_ELEM(2,___R1)
   ___END_ALLOC_LIST(3)
   ___SET_R1(___GET_LIST(3))
   ___CHECK_HEAP(2,4096)
___DEF_SLBL(2,___L2_make_2d_tree)
   ___JUMPPRM(___NOTHING,___R0)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_get_2d_data
#undef ___PH_LBL0
#define ___PH_LBL0 19
#undef ___PD_ALL
#define ___PD_ALL ___D_FP ___D_R0 ___D_R1 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_FP ___R_R0 ___R_R1 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_R1 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_get_2d_data)
___DEF_P_HLBL(___L1_get_2d_data)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_get_2d_data)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(0,1,0,0)
___DEF_GLBL(___L_get_2d_data)
   ___IF(___NOT(___EQP(___GLO(19,___G_car),___PRM(19,___G_car))))
   ___GOTO(___L2_get_2d_data)
   ___END_IF
   ___IF(___PAIRP(___R1))
   ___GOTO(___L3_get_2d_data)
   ___END_IF
___DEF_GLBL(___L2_get_2d_data)
   ___POLL(1)
___DEF_SLBL(1,___L1_get_2d_data)
   ___JUMPGLOSAFE(___SET_NARGS(1),19,___G_car)
___DEF_GLBL(___L3_get_2d_data)
   ___SET_R1(___CAR(___R1))
   ___JUMPPRM(___NOTHING,___R0)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_get_2d_left
#undef ___PH_LBL0
#define ___PH_LBL0 22
#undef ___PD_ALL
#define ___PD_ALL ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_R1 ___W_R2 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_get_2d_left)
___DEF_P_HLBL(___L1_get_2d_left)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_get_2d_left)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(0,1,0,0)
___DEF_GLBL(___L_get_2d_left)
   ___IF(___NOT(___EQP(___GLO(18,___G_cadr),___PRM(18,___G_cadr))))
   ___GOTO(___L2_get_2d_left)
   ___END_IF
   ___IF(___NOT(___PAIRP(___R1)))
   ___GOTO(___L2_get_2d_left)
   ___END_IF
   ___SET_R2(___CDR(___R1))
   ___IF(___PAIRP(___R2))
   ___GOTO(___L4_get_2d_left)
   ___END_IF
   ___GOTO(___L3_get_2d_left)
___DEF_GLBL(___L2_get_2d_left)
   ___SET_R2(___FAL)
   ___IF(___PAIRP(___R2))
   ___GOTO(___L4_get_2d_left)
   ___END_IF
___DEF_GLBL(___L3_get_2d_left)
   ___POLL(1)
___DEF_SLBL(1,___L1_get_2d_left)
   ___JUMPGLOSAFE(___SET_NARGS(1),18,___G_cadr)
___DEF_GLBL(___L4_get_2d_left)
   ___SET_R1(___CAR(___R2))
   ___JUMPPRM(___NOTHING,___R0)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_get_2d_right
#undef ___PH_LBL0
#define ___PH_LBL0 25
#undef ___PD_ALL
#define ___PD_ALL ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_R1 ___W_R2 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_get_2d_right)
___DEF_P_HLBL(___L1_get_2d_right)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_get_2d_right)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(0,1,0,0)
___DEF_GLBL(___L_get_2d_right)
   ___IF(___NOT(___EQP(___GLO(17,___G_caddr),___PRM(17,___G_caddr))))
   ___GOTO(___L2_get_2d_right)
   ___END_IF
   ___IF(___NOT(___PAIRP(___R1)))
   ___GOTO(___L2_get_2d_right)
   ___END_IF
   ___SET_R2(___CDR(___R1))
   ___IF(___PAIRP(___R2))
   ___GOTO(___L3_get_2d_right)
   ___END_IF
   ___GOTO(___L5_get_2d_right)
___DEF_GLBL(___L2_get_2d_right)
   ___SET_R2(___FAL)
   ___IF(___NOT(___PAIRP(___R2)))
   ___GOTO(___L5_get_2d_right)
   ___END_IF
___DEF_GLBL(___L3_get_2d_right)
   ___SET_R2(___CDR(___R2))
   ___IF(___PAIRP(___R2))
   ___GOTO(___L6_get_2d_right)
   ___END_IF
___DEF_GLBL(___L4_get_2d_right)
   ___POLL(1)
___DEF_SLBL(1,___L1_get_2d_right)
   ___JUMPGLOSAFE(___SET_NARGS(1),17,___G_caddr)
___DEF_GLBL(___L5_get_2d_right)
   ___SET_R2(___FAL)
   ___IF(___NOT(___PAIRP(___R2)))
   ___GOTO(___L4_get_2d_right)
   ___END_IF
___DEF_GLBL(___L6_get_2d_right)
   ___SET_R1(___CAR(___R2))
   ___JUMPPRM(___NOTHING,___R0)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_is_2d_leaf
#undef ___PH_LBL0
#define ___PH_LBL0 28
#undef ___PD_ALL
#define ___PD_ALL ___D_FP ___D_R0 ___D_R1 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_FP ___R_R0 ___R_R1 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_FP ___W_R0 ___W_R1 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_is_2d_leaf)
___DEF_P_HLBL(___L1_is_2d_leaf)
___DEF_P_HLBL(___L2_is_2d_leaf)
___DEF_P_HLBL(___L3_is_2d_leaf)
___DEF_P_HLBL(___L4_is_2d_leaf)
___DEF_P_HLBL(___L5_is_2d_leaf)
___DEF_P_HLBL(___L6_is_2d_leaf)
___DEF_P_HLBL(___L7_is_2d_leaf)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_is_2d_leaf)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(0,1,0,0)
___DEF_GLBL(___L_is_2d_leaf)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_R0(___LBL(2))
   ___ADJFP(4)
   ___POLL(1)
___DEF_SLBL(1,___L1_is_2d_leaf)
   ___JUMPGLOSAFE(___SET_NARGS(1),2,___G_get_2d_left)
___DEF_SLBL(2,___L2_is_2d_leaf)
   ___IF(___NOT(___EQP(___GLO(25,___G_null_3f_),___PRM(25,___G_null_3f_))))
   ___GOTO(___L12_is_2d_leaf)
   ___END_IF
   ___SET_R1(___BOOLEAN(___NULLP(___R1)))
   ___IF(___FALSEP(___R1))
   ___GOTO(___L8_is_2d_leaf)
   ___END_IF
   ___GOTO(___L10_is_2d_leaf)
___DEF_SLBL(3,___L3_is_2d_leaf)
   ___IF(___NOT(___FALSEP(___R1)))
   ___GOTO(___L10_is_2d_leaf)
   ___END_IF
___DEF_GLBL(___L8_is_2d_leaf)
   ___POLL(4)
___DEF_SLBL(4,___L4_is_2d_leaf)
___DEF_GLBL(___L9_is_2d_leaf)
   ___ADJFP(-4)
   ___JUMPPRM(___NOTHING,___STK(1))
___DEF_GLBL(___L10_is_2d_leaf)
   ___SET_R1(___STK(-2))
   ___SET_R0(___LBL(5))
   ___JUMPGLOSAFE(___SET_NARGS(1),3,___G_get_2d_right)
___DEF_SLBL(5,___L5_is_2d_leaf)
   ___IF(___NOT(___EQP(___GLO(25,___G_null_3f_),___PRM(25,___G_null_3f_))))
   ___GOTO(___L11_is_2d_leaf)
   ___END_IF
   ___SET_R1(___BOOLEAN(___NULLP(___R1)))
   ___POLL(6)
___DEF_SLBL(6,___L6_is_2d_leaf)
   ___GOTO(___L9_is_2d_leaf)
___DEF_GLBL(___L11_is_2d_leaf)
   ___SET_R0(___STK(-3))
   ___POLL(7)
___DEF_SLBL(7,___L7_is_2d_leaf)
   ___ADJFP(-4)
   ___JUMPGLOSAFE(___SET_NARGS(1),25,___G_null_3f_)
___DEF_GLBL(___L12_is_2d_leaf)
   ___SET_R0(___LBL(3))
   ___JUMPGLOSAFE(___SET_NARGS(1),25,___G_null_3f_)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_insert
#undef ___PH_LBL0
#define ___PH_LBL0 37
#undef ___PD_ALL
#define ___PD_ALL ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_insert)
___DEF_P_HLBL(___L1_insert)
___DEF_P_HLBL(___L2_insert)
___DEF_P_HLBL(___L3_insert)
___DEF_P_HLBL(___L4_insert)
___DEF_P_HLBL(___L5_insert)
___DEF_P_HLBL(___L6_insert)
___DEF_P_HLBL(___L7_insert)
___DEF_P_HLBL(___L8_insert)
___DEF_P_HLBL(___L9_insert)
___DEF_P_HLBL(___L10_insert)
___DEF_P_HLBL(___L11_insert)
___DEF_P_HLBL(___L12_insert)
___DEF_P_HLBL(___L13_insert)
___DEF_P_HLBL(___L14_insert)
___DEF_P_HLBL(___L15_insert)
___DEF_P_HLBL(___L16_insert)
___DEF_P_HLBL(___L17_insert)
___DEF_P_HLBL(___L18_insert)
___DEF_P_HLBL(___L19_insert)
___DEF_P_HLBL(___L20_insert)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_insert)
   ___IF_NARGS_EQ(3,___NOTHING)
   ___WRONG_NARGS(0,3,0,0)
___DEF_GLBL(___L_insert)
   ___IF(___NOT(___EQP(___GLO(25,___G_null_3f_),___PRM(25,___G_null_3f_))))
   ___GOTO(___L29_insert)
   ___END_IF
   ___IF(___NOT(___NULLP(___R2)))
   ___GOTO(___L26_insert)
   ___END_IF
   ___IF(___EQP(___GLO(23,___G_list),___PRM(23,___G_list)))
   ___GOTO(___L21_insert)
   ___END_IF
   ___GOTO(___L28_insert)
___DEF_SLBL(1,___L1_insert)
   ___IF(___FALSEP(___R1))
   ___GOTO(___L25_insert)
   ___END_IF
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___ADJFP(-8)
   ___IF(___NOT(___EQP(___GLO(23,___G_list),___PRM(23,___G_list))))
   ___GOTO(___L28_insert)
   ___END_IF
___DEF_GLBL(___L21_insert)
   ___SET_R2(___NUL)
___DEF_GLBL(___L22_insert)
   ___SET_STK(1,___R2)
   ___ADJFP(1)
   ___IF(___NOT(___EQP(___GLO(23,___G_list),___PRM(23,___G_list))))
   ___GOTO(___L24_insert)
   ___END_IF
   ___SET_R2(___NUL)
___DEF_GLBL(___L23_insert)
   ___SET_R3(___R2)
   ___SET_R2(___STK(0))
   ___POLL(2)
___DEF_SLBL(2,___L2_insert)
   ___ADJFP(-1)
   ___JUMPGLOSAFE(___SET_NARGS(3),9,___G_make_2d_tree)
___DEF_GLBL(___L24_insert)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_R0(___LBL(4))
   ___ADJFP(3)
   ___POLL(3)
___DEF_SLBL(3,___L3_insert)
   ___JUMPGLOSAFE(___SET_NARGS(0),23,___G_list)
___DEF_SLBL(4,___L4_insert)
   ___SET_R2(___R1)
   ___SET_R1(___STK(-1))
   ___SET_R0(___STK(-2))
   ___ADJFP(-3)
   ___GOTO(___L23_insert)
___DEF_GLBL(___L25_insert)
   ___SET_R3(___STK(-4))
   ___SET_R2(___STK(-5))
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___ADJFP(-8)
___DEF_GLBL(___L26_insert)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_STK(4,___R3)
   ___SET_R1(___R2)
   ___SET_R0(___LBL(6))
   ___ADJFP(8)
   ___POLL(5)
___DEF_SLBL(5,___L5_insert)
   ___JUMPGLOSAFE(___SET_NARGS(1),1,___G_get_2d_data)
___DEF_SLBL(6,___L6_insert)
   ___SET_R2(___R1)
   ___SET_R1(___STK(-6))
   ___SET_R0(___LBL(7))
   ___JUMPGENSAFE(___SET_NARGS(2),___STK(-4))
___DEF_SLBL(7,___L7_insert)
   ___IF(___NOT(___FALSEP(___R1)))
   ___GOTO(___L27_insert)
   ___END_IF
   ___SET_R1(___STK(-5))
   ___SET_R0(___LBL(8))
   ___JUMPGLOSAFE(___SET_NARGS(1),1,___G_get_2d_data)
___DEF_SLBL(8,___L8_insert)
   ___SET_STK(-3,___R1)
   ___SET_R1(___STK(-5))
   ___SET_R0(___LBL(9))
   ___JUMPGLOSAFE(___SET_NARGS(1),2,___G_get_2d_left)
___DEF_SLBL(9,___L9_insert)
   ___SET_STK(-2,___R1)
   ___SET_R1(___STK(-5))
   ___SET_R0(___LBL(10))
   ___JUMPGLOSAFE(___SET_NARGS(1),3,___G_get_2d_right)
___DEF_SLBL(10,___L10_insert)
   ___SET_R2(___R1)
   ___SET_R3(___STK(-4))
   ___SET_R1(___STK(-6))
   ___SET_R0(___LBL(11))
   ___JUMPGLOSAFE(___SET_NARGS(3),5,___G_insert)
___DEF_SLBL(11,___L11_insert)
   ___SET_R3(___R1)
   ___SET_R0(___STK(-7))
   ___SET_R2(___STK(-2))
   ___SET_R1(___STK(-3))
   ___POLL(12)
___DEF_SLBL(12,___L12_insert)
   ___ADJFP(-8)
   ___JUMPGLOSAFE(___SET_NARGS(3),9,___G_make_2d_tree)
___DEF_GLBL(___L27_insert)
   ___SET_R1(___STK(-5))
   ___SET_R0(___LBL(13))
   ___JUMPGLOSAFE(___SET_NARGS(1),1,___G_get_2d_data)
___DEF_SLBL(13,___L13_insert)
   ___SET_STK(-3,___R1)
   ___SET_R1(___STK(-5))
   ___SET_R0(___LBL(14))
   ___JUMPGLOSAFE(___SET_NARGS(1),2,___G_get_2d_left)
___DEF_SLBL(14,___L14_insert)
   ___SET_R2(___R1)
   ___SET_R3(___STK(-4))
   ___SET_R1(___STK(-6))
   ___SET_R0(___LBL(15))
   ___JUMPGLOSAFE(___SET_NARGS(3),5,___G_insert)
___DEF_SLBL(15,___L15_insert)
   ___SET_STK(-6,___R1)
   ___SET_R1(___STK(-5))
   ___SET_R0(___LBL(16))
   ___JUMPGLOSAFE(___SET_NARGS(1),3,___G_get_2d_right)
___DEF_SLBL(16,___L16_insert)
   ___SET_R3(___R1)
   ___SET_R0(___STK(-7))
   ___SET_R2(___STK(-6))
   ___SET_R1(___STK(-3))
   ___POLL(17)
___DEF_SLBL(17,___L17_insert)
   ___ADJFP(-8)
   ___JUMPGLOSAFE(___SET_NARGS(3),9,___G_make_2d_tree)
___DEF_GLBL(___L28_insert)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_R0(___LBL(19))
   ___ADJFP(4)
   ___POLL(18)
___DEF_SLBL(18,___L18_insert)
   ___JUMPGLOSAFE(___SET_NARGS(0),23,___G_list)
___DEF_SLBL(19,___L19_insert)
   ___SET_R2(___R1)
   ___SET_R1(___STK(-2))
   ___SET_R0(___STK(-3))
   ___ADJFP(-4)
   ___GOTO(___L22_insert)
___DEF_GLBL(___L29_insert)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_STK(4,___R3)
   ___SET_R1(___R2)
   ___SET_R0(___LBL(1))
   ___ADJFP(8)
   ___POLL(20)
___DEF_SLBL(20,___L20_insert)
   ___JUMPGLOSAFE(___SET_NARGS(1),25,___G_null_3f_)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_lst_2d__3e_tree
#undef ___PH_LBL0
#define ___PH_LBL0 59
#undef ___PD_ALL
#define ___PD_ALL ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_lst_2d__3e_tree)
___DEF_P_HLBL(___L1_lst_2d__3e_tree)
___DEF_P_HLBL(___L2_lst_2d__3e_tree)
___DEF_P_HLBL(___L3_lst_2d__3e_tree)
___DEF_P_HLBL(___L4_lst_2d__3e_tree)
___DEF_P_HLBL(___L5_lst_2d__3e_tree)
___DEF_P_HLBL(___L6_lst_2d__3e_tree)
___DEF_P_HLBL(___L7_lst_2d__3e_tree)
___DEF_P_HLBL(___L8_lst_2d__3e_tree)
___DEF_P_HLBL(___L9_lst_2d__3e_tree)
___DEF_P_HLBL(___L10_lst_2d__3e_tree)
___DEF_P_HLBL(___L11_lst_2d__3e_tree)
___DEF_P_HLBL(___L12_lst_2d__3e_tree)
___DEF_P_HLBL(___L13_lst_2d__3e_tree)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_lst_2d__3e_tree)
   ___IF_NARGS_EQ(2,___NOTHING)
   ___WRONG_NARGS(0,2,0,0)
___DEF_GLBL(___L_lst_2d__3e_tree)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_R0(___LBL(2))
   ___ADJFP(4)
   ___POLL(1)
___DEF_SLBL(1,___L1_lst_2d__3e_tree)
   ___JUMPGLOSAFE(___SET_NARGS(1),22,___G_length)
___DEF_SLBL(2,___L2_lst_2d__3e_tree)
   ___IF(___NOT(___EQP(___GLO(16,___G__3e_),___PRM(16,___G__3e_))))
   ___GOTO(___L26_lst_2d__3e_tree)
   ___END_IF
   ___IF(___NOT(___FIXNUMP(___R1)))
   ___GOTO(___L26_lst_2d__3e_tree)
   ___END_IF
   ___IF(___FIXGT(___R1,___FIX(1L)))
   ___GOTO(___L14_lst_2d__3e_tree)
   ___END_IF
   ___GOTO(___L19_lst_2d__3e_tree)
___DEF_SLBL(3,___L3_lst_2d__3e_tree)
   ___IF(___FALSEP(___R1))
   ___GOTO(___L19_lst_2d__3e_tree)
   ___END_IF
___DEF_GLBL(___L14_lst_2d__3e_tree)
   ___IF(___NOT(___EQP(___GLO(20,___G_cdr),___PRM(20,___G_cdr))))
   ___GOTO(___L18_lst_2d__3e_tree)
   ___END_IF
   ___IF(___NOT(___PAIRP(___STK(-2))))
   ___GOTO(___L18_lst_2d__3e_tree)
   ___END_IF
   ___SET_R1(___CDR(___STK(-2)))
___DEF_GLBL(___L15_lst_2d__3e_tree)
   ___SET_STK(0,___R1)
   ___IF(___NOT(___EQP(___GLO(19,___G_car),___PRM(19,___G_car))))
   ___GOTO(___L17_lst_2d__3e_tree)
   ___END_IF
   ___IF(___NOT(___PAIRP(___STK(-2))))
   ___GOTO(___L17_lst_2d__3e_tree)
   ___END_IF
   ___SET_R1(___CAR(___STK(-2)))
___DEF_GLBL(___L16_lst_2d__3e_tree)
   ___SET_R2(___STK(-1))
   ___SET_R3(___GLO(14,___G__3c__3d_))
   ___SET_R0(___LBL(4))
   ___ADJFP(4)
   ___JUMPGLOSAFE(___SET_NARGS(3),5,___G_insert)
___DEF_SLBL(4,___L4_lst_2d__3e_tree)
   ___SET_R2(___R1)
   ___SET_R0(___STK(-7))
   ___SET_R1(___STK(-4))
   ___POLL(5)
___DEF_SLBL(5,___L5_lst_2d__3e_tree)
   ___ADJFP(-8)
   ___JUMPGLOSAFE(___SET_NARGS(2),8,___G_lst_2d__3e_tree)
___DEF_GLBL(___L17_lst_2d__3e_tree)
   ___SET_R1(___STK(-2))
   ___SET_R0(___LBL(6))
   ___ADJFP(4)
   ___JUMPGLOSAFE(___SET_NARGS(1),19,___G_car)
___DEF_SLBL(6,___L6_lst_2d__3e_tree)
   ___ADJFP(-4)
   ___GOTO(___L16_lst_2d__3e_tree)
___DEF_GLBL(___L18_lst_2d__3e_tree)
   ___SET_R1(___STK(-2))
   ___SET_R0(___LBL(7))
   ___JUMPGLOSAFE(___SET_NARGS(1),20,___G_cdr)
___DEF_SLBL(7,___L7_lst_2d__3e_tree)
   ___GOTO(___L15_lst_2d__3e_tree)
___DEF_GLBL(___L19_lst_2d__3e_tree)
   ___SET_R1(___STK(-2))
   ___SET_R0(___LBL(8))
   ___JUMPGLOSAFE(___SET_NARGS(1),22,___G_length)
___DEF_SLBL(8,___L8_lst_2d__3e_tree)
   ___IF(___NOT(___EQP(___GLO(15,___G__3d_),___PRM(15,___G__3d_))))
   ___GOTO(___L25_lst_2d__3e_tree)
   ___END_IF
   ___IF(___NOT(___FIXNUMP(___R1)))
   ___GOTO(___L25_lst_2d__3e_tree)
   ___END_IF
   ___IF(___FIXEQ(___R1,___FIX(1L)))
   ___GOTO(___L20_lst_2d__3e_tree)
   ___END_IF
   ___GOTO(___L23_lst_2d__3e_tree)
___DEF_SLBL(9,___L9_lst_2d__3e_tree)
   ___IF(___FALSEP(___R1))
   ___GOTO(___L23_lst_2d__3e_tree)
   ___END_IF
___DEF_GLBL(___L20_lst_2d__3e_tree)
   ___IF(___NOT(___EQP(___GLO(19,___G_car),___PRM(19,___G_car))))
   ___GOTO(___L22_lst_2d__3e_tree)
   ___END_IF
   ___IF(___NOT(___PAIRP(___STK(-2))))
   ___GOTO(___L22_lst_2d__3e_tree)
   ___END_IF
   ___SET_R1(___CAR(___STK(-2)))
___DEF_GLBL(___L21_lst_2d__3e_tree)
   ___SET_R2(___STK(-1))
   ___SET_R3(___GLO(14,___G__3c__3d_))
   ___SET_R0(___STK(-3))
   ___POLL(10)
___DEF_SLBL(10,___L10_lst_2d__3e_tree)
   ___ADJFP(-4)
   ___JUMPGLOSAFE(___SET_NARGS(3),5,___G_insert)
___DEF_GLBL(___L22_lst_2d__3e_tree)
   ___SET_R1(___STK(-2))
   ___SET_R0(___LBL(11))
   ___JUMPGLOSAFE(___SET_NARGS(1),19,___G_car)
___DEF_SLBL(11,___L11_lst_2d__3e_tree)
   ___GOTO(___L21_lst_2d__3e_tree)
___DEF_GLBL(___L23_lst_2d__3e_tree)
   ___IF(___NOT(___EQP(___GLO(23,___G_list),___PRM(23,___G_list))))
   ___GOTO(___L24_lst_2d__3e_tree)
   ___END_IF
   ___SET_R1(___NUL)
   ___POLL(12)
___DEF_SLBL(12,___L12_lst_2d__3e_tree)
   ___ADJFP(-4)
   ___JUMPPRM(___NOTHING,___STK(1))
___DEF_GLBL(___L24_lst_2d__3e_tree)
   ___SET_R0(___STK(-3))
   ___POLL(13)
___DEF_SLBL(13,___L13_lst_2d__3e_tree)
   ___ADJFP(-4)
   ___JUMPGLOSAFE(___SET_NARGS(0),23,___G_list)
___DEF_GLBL(___L25_lst_2d__3e_tree)
   ___SET_R2(___FIX(1L))
   ___SET_R0(___LBL(9))
   ___JUMPGLOSAFE(___SET_NARGS(2),15,___G__3d_)
___DEF_GLBL(___L26_lst_2d__3e_tree)
   ___SET_R2(___FIX(1L))
   ___SET_R0(___LBL(3))
   ___JUMPGLOSAFE(___SET_NARGS(2),16,___G__3e_)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_in_2d_order
#undef ___PH_LBL0
#define ___PH_LBL0 74
#undef ___PD_ALL
#define ___PD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_in_2d_order)
___DEF_P_HLBL(___L1_in_2d_order)
___DEF_P_HLBL(___L2_in_2d_order)
___DEF_P_HLBL(___L3_in_2d_order)
___DEF_P_HLBL(___L4_in_2d_order)
___DEF_P_HLBL(___L5_in_2d_order)
___DEF_P_HLBL(___L6_in_2d_order)
___DEF_P_HLBL(___L7_in_2d_order)
___DEF_P_HLBL(___L8_in_2d_order)
___DEF_P_HLBL(___L9_in_2d_order)
___DEF_P_HLBL(___L10_in_2d_order)
___DEF_P_HLBL(___L11_in_2d_order)
___DEF_P_HLBL(___L12_in_2d_order)
___DEF_P_HLBL(___L13_in_2d_order)
___DEF_P_HLBL(___L14_in_2d_order)
___DEF_P_HLBL(___L15_in_2d_order)
___DEF_P_HLBL(___L16_in_2d_order)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_in_2d_order)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(0,1,0,0)
___DEF_GLBL(___L_in_2d_order)
   ___IF(___NOT(___EQP(___GLO(25,___G_null_3f_),___PRM(25,___G_null_3f_))))
   ___GOTO(___L22_in_2d_order)
   ___END_IF
   ___IF(___NOT(___NULLP(___R1)))
   ___GOTO(___L19_in_2d_order)
   ___END_IF
   ___IF(___EQP(___GLO(23,___G_list),___PRM(23,___G_list)))
   ___GOTO(___L17_in_2d_order)
   ___END_IF
   ___GOTO(___L21_in_2d_order)
___DEF_SLBL(1,___L1_in_2d_order)
   ___IF(___FALSEP(___R1))
   ___GOTO(___L18_in_2d_order)
   ___END_IF
   ___SET_R0(___STK(-3))
   ___ADJFP(-4)
   ___IF(___NOT(___EQP(___GLO(23,___G_list),___PRM(23,___G_list))))
   ___GOTO(___L21_in_2d_order)
   ___END_IF
___DEF_GLBL(___L17_in_2d_order)
   ___SET_R1(___NUL)
   ___POLL(2)
___DEF_SLBL(2,___L2_in_2d_order)
   ___JUMPPRM(___NOTHING,___R0)
___DEF_GLBL(___L18_in_2d_order)
   ___SET_R1(___STK(-2))
   ___SET_R0(___STK(-3))
   ___ADJFP(-4)
___DEF_GLBL(___L19_in_2d_order)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_R0(___LBL(4))
   ___ADJFP(4)
   ___POLL(3)
___DEF_SLBL(3,___L3_in_2d_order)
   ___JUMPGLOSAFE(___SET_NARGS(1),2,___G_get_2d_left)
___DEF_SLBL(4,___L4_in_2d_order)
   ___SET_R0(___LBL(5))
   ___JUMPGLOSAFE(___SET_NARGS(1),4,___G_in_2d_order)
___DEF_SLBL(5,___L5_in_2d_order)
   ___SET_STK(-1,___R1)
   ___SET_R0(___LBL(6))
   ___JUMPGLOSAFE(___SET_NARGS(0),24,___G_newline)
___DEF_SLBL(6,___L6_in_2d_order)
   ___SET_STK(0,___R1)
   ___SET_R1(___STK(-2))
   ___SET_R0(___LBL(7))
   ___ADJFP(4)
   ___JUMPGLOSAFE(___SET_NARGS(1),1,___G_get_2d_data)
___DEF_SLBL(7,___L7_in_2d_order)
   ___SET_R0(___LBL(8))
   ___JUMPGLOSAFE(___SET_NARGS(1),21,___G_display)
___DEF_SLBL(8,___L8_in_2d_order)
   ___SET_STK(-3,___R1)
   ___SET_R0(___LBL(9))
   ___JUMPGLOSAFE(___SET_NARGS(0),24,___G_newline)
___DEF_SLBL(9,___L9_in_2d_order)
   ___SET_STK(-2,___R1)
   ___SET_R1(___STK(-6))
   ___SET_R0(___LBL(10))
   ___JUMPGLOSAFE(___SET_NARGS(1),3,___G_get_2d_right)
___DEF_SLBL(10,___L10_in_2d_order)
   ___SET_R0(___LBL(11))
   ___JUMPGLOSAFE(___SET_NARGS(1),4,___G_in_2d_order)
___DEF_SLBL(11,___L11_in_2d_order)
   ___IF(___NOT(___EQP(___GLO(23,___G_list),___PRM(23,___G_list))))
   ___GOTO(___L20_in_2d_order)
   ___END_IF
   ___BEGIN_ALLOC_LIST(5,___R1)
   ___ADD_LIST_ELEM(1,___STK(-2))
   ___ADD_LIST_ELEM(2,___STK(-3))
   ___ADD_LIST_ELEM(3,___STK(-4))
   ___ADD_LIST_ELEM(4,___STK(-5))
   ___END_ALLOC_LIST(5)
   ___SET_R1(___GET_LIST(5))
   ___CHECK_HEAP(12,4096)
___DEF_SLBL(12,___L12_in_2d_order)
   ___POLL(13)
___DEF_SLBL(13,___L13_in_2d_order)
   ___ADJFP(-8)
   ___JUMPPRM(___NOTHING,___STK(1))
___DEF_GLBL(___L20_in_2d_order)
   ___SET_STK(-6,___STK(-7))
   ___SET_STK(-7,___STK(-5))
   ___SET_STK(-5,___STK(-6))
   ___SET_STK(-6,___STK(-4))
   ___SET_R3(___R1)
   ___SET_R2(___STK(-2))
   ___SET_R1(___STK(-3))
   ___SET_R0(___STK(-5))
   ___POLL(14)
___DEF_SLBL(14,___L14_in_2d_order)
   ___ADJFP(-6)
   ___JUMPGLOSAFE(___SET_NARGS(5),23,___G_list)
___DEF_GLBL(___L21_in_2d_order)
   ___POLL(15)
___DEF_SLBL(15,___L15_in_2d_order)
   ___JUMPGLOSAFE(___SET_NARGS(0),23,___G_list)
___DEF_GLBL(___L22_in_2d_order)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_R0(___LBL(1))
   ___ADJFP(4)
   ___POLL(16)
___DEF_SLBL(16,___L16_in_2d_order)
   ___JUMPGLOSAFE(___SET_NARGS(1),25,___G_null_3f_)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_num_2d_leaves
#undef ___PH_LBL0
#define ___PH_LBL0 92
#undef ___PD_ALL
#define ___PD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R4 ___D_F64(___F64V1) ___D_F64(___F64V2) \
 ___D_F64(___F64V3)
#undef ___PR_ALL
#define ___PR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_num_2d_leaves)
___DEF_P_HLBL(___L1_num_2d_leaves)
___DEF_P_HLBL(___L2_num_2d_leaves)
___DEF_P_HLBL(___L3_num_2d_leaves)
___DEF_P_HLBL(___L4_num_2d_leaves)
___DEF_P_HLBL(___L5_num_2d_leaves)
___DEF_P_HLBL(___L6_num_2d_leaves)
___DEF_P_HLBL(___L7_num_2d_leaves)
___DEF_P_HLBL(___L8_num_2d_leaves)
___DEF_P_HLBL(___L9_num_2d_leaves)
___DEF_P_HLBL(___L10_num_2d_leaves)
___DEF_P_HLBL(___L11_num_2d_leaves)
___DEF_P_HLBL(___L12_num_2d_leaves)
___DEF_P_HLBL(___L13_num_2d_leaves)
___DEF_P_HLBL(___L14_num_2d_leaves)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_num_2d_leaves)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(0,1,0,0)
___DEF_GLBL(___L_num_2d_leaves)
   ___IF(___NOT(___EQP(___GLO(25,___G_null_3f_),___PRM(25,___G_null_3f_))))
   ___GOTO(___L24_num_2d_leaves)
   ___END_IF
   ___IF(___NULLP(___R1))
   ___GOTO(___L15_num_2d_leaves)
   ___END_IF
   ___GOTO(___L17_num_2d_leaves)
___DEF_SLBL(1,___L1_num_2d_leaves)
   ___IF(___FALSEP(___R1))
   ___GOTO(___L16_num_2d_leaves)
   ___END_IF
   ___SET_R0(___STK(-3))
   ___ADJFP(-4)
___DEF_GLBL(___L15_num_2d_leaves)
   ___SET_R1(___FIX(0L))
   ___POLL(2)
___DEF_SLBL(2,___L2_num_2d_leaves)
   ___JUMPPRM(___NOTHING,___R0)
___DEF_GLBL(___L16_num_2d_leaves)
   ___SET_R1(___STK(-2))
   ___SET_R0(___STK(-3))
   ___ADJFP(-4)
___DEF_GLBL(___L17_num_2d_leaves)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_R0(___LBL(4))
   ___ADJFP(4)
   ___POLL(3)
___DEF_SLBL(3,___L3_num_2d_leaves)
   ___JUMPGLOSAFE(___SET_NARGS(1),7,___G_is_2d_leaf)
___DEF_SLBL(4,___L4_num_2d_leaves)
   ___IF(___FALSEP(___R1))
   ___GOTO(___L23_num_2d_leaves)
   ___END_IF
   ___SET_R1(___FIX(1L))
   ___POLL(5)
___DEF_SLBL(5,___L5_num_2d_leaves)
   ___GOTO(___L19_num_2d_leaves)
___DEF_SLBL(6,___L6_num_2d_leaves)
   ___IF(___NOT(___EQP(___GLO(12,___G__2b_),___PRM(12,___G__2b_))))
   ___GOTO(___L21_num_2d_leaves)
   ___END_IF
   ___IF(___NOT(___FIXNUMP(___R1)))
   ___GOTO(___L18_num_2d_leaves)
   ___END_IF
   ___IF(___FIXNUMP(___STK(-1)))
   ___GOTO(___L20_num_2d_leaves)
   ___END_IF
___DEF_GLBL(___L18_num_2d_leaves)
   ___IF(___NOT(___FLONUMP(___R1)))
   ___GOTO(___L21_num_2d_leaves)
   ___END_IF
   ___IF(___NOT(___FLONUMP(___STK(-1))))
   ___GOTO(___L21_num_2d_leaves)
   ___END_IF
   ___SET_F64(___F64V1,___F64UNBOX(___STK(-1)))
   ___SET_F64(___F64V2,___F64UNBOX(___R1))
   ___SET_F64(___F64V3,___F64ADD(___F64V1,___F64V2))
   ___SET_R1(___F64BOX(___F64V3))
   ___CHECK_HEAP(7,4096)
___DEF_SLBL(7,___L7_num_2d_leaves)
   ___POLL(8)
___DEF_SLBL(8,___L8_num_2d_leaves)
___DEF_GLBL(___L19_num_2d_leaves)
   ___ADJFP(-4)
   ___JUMPPRM(___NOTHING,___STK(1))
___DEF_GLBL(___L20_num_2d_leaves)
   ___SET_R2(___FIXADDP(___STK(-1),___R1))
   ___IF(___NOT(___FALSEP(___R2)))
   ___GOTO(___L22_num_2d_leaves)
   ___END_IF
___DEF_GLBL(___L21_num_2d_leaves)
   ___SET_R2(___R1)
   ___SET_R1(___STK(-1))
   ___SET_R0(___STK(-3))
   ___POLL(9)
___DEF_SLBL(9,___L9_num_2d_leaves)
   ___ADJFP(-4)
   ___JUMPGLOSAFE(___SET_NARGS(2),12,___G__2b_)
___DEF_GLBL(___L22_num_2d_leaves)
   ___SET_R1(___R2)
   ___POLL(10)
___DEF_SLBL(10,___L10_num_2d_leaves)
   ___GOTO(___L19_num_2d_leaves)
___DEF_GLBL(___L23_num_2d_leaves)
   ___SET_R1(___STK(-2))
   ___SET_R0(___LBL(11))
   ___JUMPGLOSAFE(___SET_NARGS(1),2,___G_get_2d_left)
___DEF_SLBL(11,___L11_num_2d_leaves)
   ___SET_R0(___LBL(12))
   ___JUMPGLOSAFE(___SET_NARGS(1),10,___G_num_2d_leaves)
___DEF_SLBL(12,___L12_num_2d_leaves)
   ___SET_STK(-1,___R1)
   ___SET_R1(___STK(-2))
   ___SET_R0(___LBL(13))
   ___JUMPGLOSAFE(___SET_NARGS(1),3,___G_get_2d_right)
___DEF_SLBL(13,___L13_num_2d_leaves)
   ___SET_R0(___LBL(6))
   ___JUMPGLOSAFE(___SET_NARGS(1),10,___G_num_2d_leaves)
___DEF_GLBL(___L24_num_2d_leaves)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_R0(___LBL(1))
   ___ADJFP(4)
   ___POLL(14)
___DEF_SLBL(14,___L14_num_2d_leaves)
   ___JUMPGLOSAFE(___SET_NARGS(1),25,___G_null_3f_)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_is_2d_in
#undef ___PH_LBL0
#define ___PH_LBL0 108
#undef ___PD_ALL
#define ___PD_ALL ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R4 ___D_F64(___F64V1) ___D_F64(___F64V2) ___D_F64( \
___F64V3)
#undef ___PR_ALL
#define ___PR_ALL ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_is_2d_in)
___DEF_P_HLBL(___L1_is_2d_in)
___DEF_P_HLBL(___L2_is_2d_in)
___DEF_P_HLBL(___L3_is_2d_in)
___DEF_P_HLBL(___L4_is_2d_in)
___DEF_P_HLBL(___L5_is_2d_in)
___DEF_P_HLBL(___L6_is_2d_in)
___DEF_P_HLBL(___L7_is_2d_in)
___DEF_P_HLBL(___L8_is_2d_in)
___DEF_P_HLBL(___L9_is_2d_in)
___DEF_P_HLBL(___L10_is_2d_in)
___DEF_P_HLBL(___L11_is_2d_in)
___DEF_P_HLBL(___L12_is_2d_in)
___DEF_P_HLBL(___L13_is_2d_in)
___DEF_P_HLBL(___L14_is_2d_in)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_is_2d_in)
   ___IF_NARGS_EQ(2,___NOTHING)
   ___WRONG_NARGS(0,2,0,0)
___DEF_GLBL(___L_is_2d_in)
   ___IF(___NOT(___EQP(___GLO(25,___G_null_3f_),___PRM(25,___G_null_3f_))))
   ___GOTO(___L31_is_2d_in)
   ___END_IF
   ___IF(___NULLP(___R2))
   ___GOTO(___L15_is_2d_in)
   ___END_IF
   ___GOTO(___L17_is_2d_in)
___DEF_SLBL(1,___L1_is_2d_in)
   ___IF(___FALSEP(___R1))
   ___GOTO(___L16_is_2d_in)
   ___END_IF
   ___SET_R0(___STK(-3))
   ___ADJFP(-4)
___DEF_GLBL(___L15_is_2d_in)
   ___SET_R1(___FAL)
   ___POLL(2)
___DEF_SLBL(2,___L2_is_2d_in)
   ___JUMPPRM(___NOTHING,___R0)
___DEF_GLBL(___L16_is_2d_in)
   ___SET_R2(___STK(-1))
   ___SET_R1(___STK(-2))
   ___SET_R0(___STK(-3))
   ___ADJFP(-4)
___DEF_GLBL(___L17_is_2d_in)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_R1(___R2)
   ___SET_R0(___LBL(4))
   ___ADJFP(4)
   ___POLL(3)
___DEF_SLBL(3,___L3_is_2d_in)
   ___JUMPGLOSAFE(___SET_NARGS(1),1,___G_get_2d_data)
___DEF_SLBL(4,___L4_is_2d_in)
   ___IF(___NOT(___EQP(___GLO(15,___G__3d_),___PRM(15,___G__3d_))))
   ___GOTO(___L21_is_2d_in)
   ___END_IF
   ___IF(___NOT(___FIXNUMP(___R1)))
   ___GOTO(___L18_is_2d_in)
   ___END_IF
   ___IF(___NOT(___FIXNUMP(___STK(-2))))
   ___GOTO(___L18_is_2d_in)
   ___END_IF
   ___IF(___FIXEQ(___STK(-2),___R1))
   ___GOTO(___L19_is_2d_in)
   ___END_IF
   ___GOTO(___L22_is_2d_in)
___DEF_GLBL(___L18_is_2d_in)
   ___IF(___NOT(___FLONUMP(___R1)))
   ___GOTO(___L21_is_2d_in)
   ___END_IF
   ___IF(___NOT(___FLONUMP(___STK(-2))))
   ___GOTO(___L21_is_2d_in)
   ___END_IF
   ___SET_F64(___F64V1,___F64UNBOX(___STK(-2)))
   ___SET_F64(___F64V2,___F64UNBOX(___R1))
   ___IF(___NOT(___F64EQ(___F64V1,___F64V2)))
   ___GOTO(___L22_is_2d_in)
   ___END_IF
___DEF_GLBL(___L19_is_2d_in)
   ___SET_R1(___TRU)
   ___POLL(5)
___DEF_SLBL(5,___L5_is_2d_in)
___DEF_GLBL(___L20_is_2d_in)
   ___ADJFP(-4)
   ___JUMPPRM(___NOTHING,___STK(1))
___DEF_GLBL(___L21_is_2d_in)
   ___SET_R2(___R1)
   ___SET_R1(___STK(-2))
   ___SET_R0(___LBL(6))
   ___JUMPGLOSAFE(___SET_NARGS(2),15,___G__3d_)
___DEF_SLBL(6,___L6_is_2d_in)
   ___IF(___NOT(___FALSEP(___R1)))
   ___GOTO(___L19_is_2d_in)
   ___END_IF
___DEF_GLBL(___L22_is_2d_in)
   ___SET_R1(___STK(-1))
   ___SET_R0(___LBL(7))
   ___JUMPGLOSAFE(___SET_NARGS(1),1,___G_get_2d_data)
___DEF_SLBL(7,___L7_is_2d_in)
   ___IF(___NOT(___EQP(___GLO(13,___G__3c_),___PRM(13,___G__3c_))))
   ___GOTO(___L25_is_2d_in)
   ___END_IF
   ___IF(___NOT(___FIXNUMP(___R1)))
   ___GOTO(___L23_is_2d_in)
   ___END_IF
   ___IF(___NOT(___FIXNUMP(___STK(-2))))
   ___GOTO(___L23_is_2d_in)
   ___END_IF
   ___IF(___FIXLT(___STK(-2),___R1))
   ___GOTO(___L24_is_2d_in)
   ___END_IF
   ___GOTO(___L26_is_2d_in)
___DEF_GLBL(___L23_is_2d_in)
   ___IF(___NOT(___FLONUMP(___R1)))
   ___GOTO(___L25_is_2d_in)
   ___END_IF
   ___IF(___NOT(___FLONUMP(___STK(-2))))
   ___GOTO(___L25_is_2d_in)
   ___END_IF
   ___SET_F64(___F64V1,___F64UNBOX(___STK(-2)))
   ___SET_F64(___F64V2,___F64UNBOX(___R1))
   ___IF(___NOT(___F64LT(___F64V1,___F64V2)))
   ___GOTO(___L26_is_2d_in)
   ___END_IF
___DEF_GLBL(___L24_is_2d_in)
   ___SET_R1(___STK(-1))
   ___SET_R0(___LBL(8))
   ___JUMPGLOSAFE(___SET_NARGS(1),2,___G_get_2d_left)
___DEF_SLBL(8,___L8_is_2d_in)
   ___SET_R2(___R1)
   ___SET_R1(___STK(-2))
   ___SET_R0(___STK(-3))
   ___POLL(9)
___DEF_SLBL(9,___L9_is_2d_in)
   ___ADJFP(-4)
   ___JUMPGLOSAFE(___SET_NARGS(2),6,___G_is_2d_in)
___DEF_GLBL(___L25_is_2d_in)
   ___SET_R2(___R1)
   ___SET_R1(___STK(-2))
   ___SET_R0(___LBL(10))
   ___JUMPGLOSAFE(___SET_NARGS(2),13,___G__3c_)
___DEF_SLBL(10,___L10_is_2d_in)
   ___IF(___NOT(___FALSEP(___R1)))
   ___GOTO(___L24_is_2d_in)
   ___END_IF
___DEF_GLBL(___L26_is_2d_in)
   ___SET_R1(___STK(-1))
   ___SET_R0(___LBL(11))
   ___JUMPGLOSAFE(___SET_NARGS(1),1,___G_get_2d_data)
___DEF_SLBL(11,___L11_is_2d_in)
   ___IF(___NOT(___EQP(___GLO(16,___G__3e_),___PRM(16,___G__3e_))))
   ___GOTO(___L29_is_2d_in)
   ___END_IF
   ___IF(___NOT(___FIXNUMP(___R1)))
   ___GOTO(___L27_is_2d_in)
   ___END_IF
   ___IF(___NOT(___FIXNUMP(___STK(-2))))
   ___GOTO(___L27_is_2d_in)
   ___END_IF
   ___IF(___FIXGT(___STK(-2),___R1))
   ___GOTO(___L30_is_2d_in)
   ___END_IF
   ___GOTO(___L28_is_2d_in)
___DEF_GLBL(___L27_is_2d_in)
   ___IF(___NOT(___FLONUMP(___R1)))
   ___GOTO(___L29_is_2d_in)
   ___END_IF
   ___IF(___NOT(___FLONUMP(___STK(-2))))
   ___GOTO(___L29_is_2d_in)
   ___END_IF
   ___SET_F64(___F64V1,___F64UNBOX(___STK(-2)))
   ___SET_F64(___F64V2,___F64UNBOX(___R1))
   ___IF(___F64GT(___F64V1,___F64V2))
   ___GOTO(___L30_is_2d_in)
   ___END_IF
___DEF_GLBL(___L28_is_2d_in)
   ___SET_R1(___VOID)
   ___POLL(12)
___DEF_SLBL(12,___L12_is_2d_in)
   ___GOTO(___L20_is_2d_in)
___DEF_GLBL(___L29_is_2d_in)
   ___SET_R2(___R1)
   ___SET_R1(___STK(-2))
   ___SET_R0(___LBL(13))
   ___JUMPGLOSAFE(___SET_NARGS(2),16,___G__3e_)
___DEF_SLBL(13,___L13_is_2d_in)
   ___IF(___FALSEP(___R1))
   ___GOTO(___L28_is_2d_in)
   ___END_IF
___DEF_GLBL(___L30_is_2d_in)
   ___SET_R1(___STK(-1))
   ___SET_R0(___LBL(8))
   ___JUMPGLOSAFE(___SET_NARGS(1),3,___G_get_2d_right)
___DEF_GLBL(___L31_is_2d_in)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_R1(___R2)
   ___SET_R0(___LBL(1))
   ___ADJFP(4)
   ___POLL(14)
___DEF_SLBL(14,___L14_is_2d_in)
   ___JUMPGLOSAFE(___SET_NARGS(1),25,___G_null_3f_)
___END_P_SW
___END_P_COD

___END_M_SW
___END_M_COD

___BEGIN_LBL
 ___DEF_LBL_INTRO(___H__20_tree," tree",___REF_FAL,13,0)
,___DEF_LBL_PROC(___H__20_tree,0,0)
,___DEF_LBL_RET(___H__20_tree,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H__20_tree,___IFD(___RETN,3,0,0x1L))
,___DEF_LBL_RET(___H__20_tree,___IFD(___RETN,3,0,0x3L))
,___DEF_LBL_RET(___H__20_tree,___IFD(___RETN,3,0,0x1L))
,___DEF_LBL_RET(___H__20_tree,___IFD(___RETN,3,0,0x1L))
,___DEF_LBL_RET(___H__20_tree,___IFD(___RETN,3,0,0x1L))
,___DEF_LBL_RET(___H__20_tree,___IFD(___RETN,3,0,0x1L))
,___DEF_LBL_RET(___H__20_tree,___IFD(___RETN,3,0,0x1L))
,___DEF_LBL_RET(___H__20_tree,___IFD(___RETN,3,0,0x1L))
,___DEF_LBL_RET(___H__20_tree,___IFD(___RETN,3,0,0x1L))
,___DEF_LBL_RET(___H__20_tree,___IFD(___RETN,3,0,0x1L))
,___DEF_LBL_RET(___H__20_tree,___IFD(___RETI,4,4,0x3f0L))
,___DEF_LBL_INTRO(___H_make_2d_tree,0,___REF_FAL,3,0)
,___DEF_LBL_PROC(___H_make_2d_tree,3,0)
,___DEF_LBL_RET(___H_make_2d_tree,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_make_2d_tree,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_INTRO(___H_get_2d_data,0,___REF_FAL,2,0)
,___DEF_LBL_PROC(___H_get_2d_data,1,0)
,___DEF_LBL_RET(___H_get_2d_data,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_INTRO(___H_get_2d_left,0,___REF_FAL,2,0)
,___DEF_LBL_PROC(___H_get_2d_left,1,0)
,___DEF_LBL_RET(___H_get_2d_left,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_INTRO(___H_get_2d_right,0,___REF_FAL,2,0)
,___DEF_LBL_PROC(___H_get_2d_right,1,0)
,___DEF_LBL_RET(___H_get_2d_right,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_INTRO(___H_is_2d_leaf,0,___REF_FAL,8,0)
,___DEF_LBL_PROC(___H_is_2d_leaf,1,0)
,___DEF_LBL_RET(___H_is_2d_leaf,___IFD(___RETI,4,0,0x3f3L))
,___DEF_LBL_RET(___H_is_2d_leaf,___IFD(___RETN,3,0,0x3L))
,___DEF_LBL_RET(___H_is_2d_leaf,___IFD(___RETN,3,0,0x3L))
,___DEF_LBL_RET(___H_is_2d_leaf,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_is_2d_leaf,___IFD(___RETN,3,0,0x1L))
,___DEF_LBL_RET(___H_is_2d_leaf,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_is_2d_leaf,___IFD(___RETI,4,4,0x3f0L))
,___DEF_LBL_INTRO(___H_insert,0,___REF_FAL,21,0)
,___DEF_LBL_PROC(___H_insert,3,0)
,___DEF_LBL_RET(___H_insert,___IFD(___RETN,7,0,0xfL))
,___DEF_LBL_RET(___H_insert,___IFD(___RETI,1,4,0x3f1L))
,___DEF_LBL_RET(___H_insert,___IFD(___RETI,4,1,0x3f7L))
,___DEF_LBL_RET(___H_insert,___IFD(___RETN,3,1,0x7L))
,___DEF_LBL_RET(___H_insert,___IFD(___RETI,8,0,0x3f0fL))
,___DEF_LBL_RET(___H_insert,___IFD(___RETN,7,0,0xfL))
,___DEF_LBL_RET(___H_insert,___IFD(___RETN,7,0,0xfL))
,___DEF_LBL_RET(___H_insert,___IFD(___RETN,7,0,0xfL))
,___DEF_LBL_RET(___H_insert,___IFD(___RETN,7,0,0x1fL))
,___DEF_LBL_RET(___H_insert,___IFD(___RETN,7,0,0x3bL))
,___DEF_LBL_RET(___H_insert,___IFD(___RETN,7,0,0x31L))
,___DEF_LBL_RET(___H_insert,___IFD(___RETI,8,8,0x3f30L))
,___DEF_LBL_RET(___H_insert,___IFD(___RETN,7,0,0xfL))
,___DEF_LBL_RET(___H_insert,___IFD(___RETN,7,0,0x1fL))
,___DEF_LBL_RET(___H_insert,___IFD(___RETN,7,0,0x15L))
,___DEF_LBL_RET(___H_insert,___IFD(___RETN,7,0,0x13L))
,___DEF_LBL_RET(___H_insert,___IFD(___RETI,8,8,0x3f12L))
,___DEF_LBL_RET(___H_insert,___IFD(___RETI,4,0,0x3f3L))
,___DEF_LBL_RET(___H_insert,___IFD(___RETN,3,0,0x3L))
,___DEF_LBL_RET(___H_insert,___IFD(___RETI,8,0,0x3f0fL))
,___DEF_LBL_INTRO(___H_lst_2d__3e_tree,0,___REF_FAL,14,0)
,___DEF_LBL_PROC(___H_lst_2d__3e_tree,2,0)
,___DEF_LBL_RET(___H_lst_2d__3e_tree,___IFD(___RETI,4,0,0x3f7L))
,___DEF_LBL_RET(___H_lst_2d__3e_tree,___IFD(___RETN,3,0,0x7L))
,___DEF_LBL_RET(___H_lst_2d__3e_tree,___IFD(___RETN,3,0,0x7L))
,___DEF_LBL_RET(___H_lst_2d__3e_tree,___IFD(___RETN,7,0,0x9L))
,___DEF_LBL_RET(___H_lst_2d__3e_tree,___IFD(___RETI,8,8,0x3f08L))
,___DEF_LBL_RET(___H_lst_2d__3e_tree,___IFD(___RETN,7,0,0xdL))
,___DEF_LBL_RET(___H_lst_2d__3e_tree,___IFD(___RETN,3,0,0x7L))
,___DEF_LBL_RET(___H_lst_2d__3e_tree,___IFD(___RETN,3,0,0x7L))
,___DEF_LBL_RET(___H_lst_2d__3e_tree,___IFD(___RETN,3,0,0x7L))
,___DEF_LBL_RET(___H_lst_2d__3e_tree,___IFD(___RETI,4,4,0x3f0L))
,___DEF_LBL_RET(___H_lst_2d__3e_tree,___IFD(___RETN,3,0,0x5L))
,___DEF_LBL_RET(___H_lst_2d__3e_tree,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_lst_2d__3e_tree,___IFD(___RETI,4,4,0x3f0L))
,___DEF_LBL_INTRO(___H_in_2d_order,0,___REF_FAL,17,0)
,___DEF_LBL_PROC(___H_in_2d_order,1,0)
,___DEF_LBL_RET(___H_in_2d_order,___IFD(___RETN,3,0,0x3L))
,___DEF_LBL_RET(___H_in_2d_order,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_in_2d_order,___IFD(___RETI,4,0,0x3f3L))
,___DEF_LBL_RET(___H_in_2d_order,___IFD(___RETN,3,0,0x3L))
,___DEF_LBL_RET(___H_in_2d_order,___IFD(___RETN,3,0,0x3L))
,___DEF_LBL_RET(___H_in_2d_order,___IFD(___RETN,3,0,0x7L))
,___DEF_LBL_RET(___H_in_2d_order,___IFD(___RETN,7,0,0xfL))
,___DEF_LBL_RET(___H_in_2d_order,___IFD(___RETN,7,0,0xfL))
,___DEF_LBL_RET(___H_in_2d_order,___IFD(___RETN,7,0,0x1fL))
,___DEF_LBL_RET(___H_in_2d_order,___IFD(___RETN,7,0,0x3dL))
,___DEF_LBL_RET(___H_in_2d_order,___IFD(___RETN,7,0,0x3dL))
,___DEF_LBL_RET(___H_in_2d_order,___IFD(___RETI,8,0,0x3f01L))
,___DEF_LBL_RET(___H_in_2d_order,___IFD(___RETI,8,0,0x3f01L))
,___DEF_LBL_RET(___H_in_2d_order,___IFD(___RETI,8,8,0x3f03L))
,___DEF_LBL_RET(___H_in_2d_order,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_in_2d_order,___IFD(___RETI,4,0,0x3f3L))
,___DEF_LBL_INTRO(___H_num_2d_leaves,0,___REF_FAL,15,0)
,___DEF_LBL_PROC(___H_num_2d_leaves,1,0)
,___DEF_LBL_RET(___H_num_2d_leaves,___IFD(___RETN,3,0,0x3L))
,___DEF_LBL_RET(___H_num_2d_leaves,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_num_2d_leaves,___IFD(___RETI,4,0,0x3f3L))
,___DEF_LBL_RET(___H_num_2d_leaves,___IFD(___RETN,3,0,0x3L))
,___DEF_LBL_RET(___H_num_2d_leaves,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_num_2d_leaves,___IFD(___RETN,3,0,0x5L))
,___DEF_LBL_RET(___H_num_2d_leaves,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_num_2d_leaves,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_num_2d_leaves,___IFD(___RETI,4,4,0x3f0L))
,___DEF_LBL_RET(___H_num_2d_leaves,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_num_2d_leaves,___IFD(___RETN,3,0,0x3L))
,___DEF_LBL_RET(___H_num_2d_leaves,___IFD(___RETN,3,0,0x3L))
,___DEF_LBL_RET(___H_num_2d_leaves,___IFD(___RETN,3,0,0x5L))
,___DEF_LBL_RET(___H_num_2d_leaves,___IFD(___RETI,4,0,0x3f3L))
,___DEF_LBL_INTRO(___H_is_2d_in,0,___REF_FAL,15,0)
,___DEF_LBL_PROC(___H_is_2d_in,2,0)
,___DEF_LBL_RET(___H_is_2d_in,___IFD(___RETN,3,0,0x7L))
,___DEF_LBL_RET(___H_is_2d_in,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_is_2d_in,___IFD(___RETI,4,0,0x3f7L))
,___DEF_LBL_RET(___H_is_2d_in,___IFD(___RETN,3,0,0x7L))
,___DEF_LBL_RET(___H_is_2d_in,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_is_2d_in,___IFD(___RETN,3,0,0x7L))
,___DEF_LBL_RET(___H_is_2d_in,___IFD(___RETN,3,0,0x7L))
,___DEF_LBL_RET(___H_is_2d_in,___IFD(___RETN,3,0,0x3L))
,___DEF_LBL_RET(___H_is_2d_in,___IFD(___RETI,4,4,0x3f0L))
,___DEF_LBL_RET(___H_is_2d_in,___IFD(___RETN,3,0,0x7L))
,___DEF_LBL_RET(___H_is_2d_in,___IFD(___RETN,3,0,0x7L))
,___DEF_LBL_RET(___H_is_2d_in,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_is_2d_in,___IFD(___RETN,3,0,0x7L))
,___DEF_LBL_RET(___H_is_2d_in,___IFD(___RETI,4,0,0x3f7L))
___END_LBL

___BEGIN_MOD1
___DEF_PRM(0,___G__20_tree,1)
___END_MOD1

___BEGIN_MOD2
___END_MOD2

#endif
